# Generated by Django 4.2.27 on 2025-12-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_status',
            field=models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
