# Generated by Django 4.2.27 on 2025-12-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_admission', '0002_patient_admission_status_patient_discharged_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
